### ISSUE TITLE
rodio

### ISSUE THREAD

**Issue by jwinarske** [TheBerkin/creak#3]
isn't this a re-brand of [Rodio](https://github.com/RustAudio/rodio) with a few changes?

**Comment by TheBerkin** [comment]
Not really.

While they do share the same audio decoding dependencies, they don't serve the same purpose at all. Rodio is an audio playback engine; this crate is just a sample converter (which can't play sounds). Ideally, you would use this crate as part of a playback engine's backend to load sound data. Since I just wanted something to load + convert samples, I wrote this crate.

Closing this issue for now.

**Comment by TheBerkin** [comment]
Nope.

While they do share the same audio decoding dependencies, they don't serve the same purpose at all. Rodio is an audio playback engine; this crate is just a sample converter (which can't play sounds). Ideally, you would use this crate as part of a playback engine's backend to load sound data. Since I just wanted something to load + convert samples, I wrote this crate.

Closing this issue for now.
